### ISSUE TITLE
Series of pre-selectable charts

### ISSUE THREAD

**Issue by Skippern** [OpenSeaMap/chart-designer#1]
There should be a list of pre-selectable charts following the same cut and resolutions as the INT (international) chart series. Each chart in this list should use the INT number and the international name of the chart. If applicable and if it doesn't make a too complicated system, national names in different languages might be added later.

**Comment by ehrenfeu** [comment]
That goes well along with what we've discussed a while ago on the mailing list. Do you know a list with all INT charts and maybe even something like their bounding boxes?

**Comment by Skippern** [comment]
Unfortunately not though I think I can get those based on BR, AR, NZ and US, and probably soon NO charts. If I can find a consolidated list I will sure share it here.

**Comment by Skippern** [comment]
You should add a file where predefined chart cuts can be defined, I'll fork the repo and add what I can identify than, for you to pull when I have identified as many as I can find.

That way we might also be able to add national chart folias as well.

As soon as I have a fork with a file in a proper format, don't know what is best, but guessing XML or JSON (I need to read up on JSON format though)

What camps would we need to create such chart folias?

* INT number
* INT name
* max lat
* min lat
* max lon
* min lon
* published scale

Anything more?

* National number (prefixed by country code?)
* National name

**Comment by Skippern** [comment]
Opps, didn't mean to close it

**Comment by ehrenfeu** [comment]
Your list ist pretty much complete, I'd say. Maybe something like the date of the first and the last (current) publication of the official charts, as a reference. But I'm not sure this is really necessary.

**Comment by Skippern** [comment]
If you add a sample file of whatever format you think is best for you, I fork off and start adding the data

**Comment by ehrenfeu** [comment]
That's probably something we should rather ask @humbach as he is the author of this tool. I'm willing to contribute some scripts to auto-generate stuff, but therefore the "central" tool has to be in place before :smirk: 

On the other hand, the above points basically also apply to @rahra 's `smrender` and the Garmin generation scripts (probably). I'll try to think about a format that makes sense in the next days, ok? Feel free to nag me in case I forget :smile: 

In the meantime I'll create an issue in the "general" tracker to set up infrastructure for generating all these things...

**Comment by rahra** [comment]
For Croatia, I created a list of all charts with their parameters once. I use it to create these Smrender charts: http://www.abenteuerland.at/download/smrender/charts/croatia/yellow_map/PDF/ 
Of course I can make the list public.

There's also these large scale charts: https://sailingaroundtheworld.wordpress.com/ubersegler/
I assume that there is a list of chart parameters as well. We can ask Christian.

**Comment by ehrenfeu** [comment]
That would be great if you could make your list available. I'd suggest to place stuff like bounding-box-lists etc. in a separate repository, as this is clearly a generic thing which is relevant for many of the other tools in the various repos...

**Comment by malcolmh** [comment]
On 23 Jan 2015, at 10:20, Niko Ehrenfeuchter <notifications@github.com> wrote:
> 
>  I'd suggest to place stuff like bounding-box-lists etc. in a separate repository

How about the “General” repo?=

**Comment by ehrenfeu** [comment]
I wouldn't want to put it there, as the `general` one is really meant for generic project stuff.

Coordinates and properties of bounding boxes are something very specific, although relevant for multiple different parts of the project itself.

If you're ok with it, I'd just create a repo `charts-properties` ...?

**Comment by ehrenfeu** [comment]
Created the repository [chart-sheet-properties](https://github.com/OpenSeaMap/chart-sheet-properties) as Alexej asked me (via PM) where to put the example catalog that he created. I think we can continue discussing about the proper layout of the catalog there.

**Comment by Skippern** [comment]
Best way forward would be getting RW+ for anybody who want to contribute or should we fork?

**Comment by ehrenfeu** [comment]
@Skippern I agree, but unfortunately I can only give write access to members of the "Admin" team. Currently, only @Nautic (Markus) can create a new team and assign those permissions.

Therefore I'd say let's just go with forks and pull requests (those, I'm allowed to process...) until Markus is reading his email again.

**Comment by Skippern** [comment]
@ehrenfeu Probably safer, have 1 or 2 admins, and run over fork/pulls, I'll wait for the examples to enter the repo, and fork off to do C1 and C2 (South America)

**Comment by malcolmh** [comment]
Spread sheet format would be appropriate for this, say one file for each of the S-11 sections. Not only could a spreadsheet program be used for the data preparation, but if saved in CSV format, it would be easy to process by an automated chart generating system.=

**Comment by malcolmh** [comment]
Ah! I see that Dirk is ahead of the curve!

This discussion has got bifurcated into two different repo issues. Is it possible to merge them?

**Comment by Dirk--** [comment]
tried to concentrate the issues at:
http://wiki.openseamap.org/wiki/OpenSeaMap-dev:Catalogue_of_INT_Charts
Did I miss anything?

**Comment by ehrenfeu** [comment]
@malcolmh it's true that this issue is now kind of forked into two separate ones. As this one is in the repository `chart-designer`, but the discussion is more a generic one, I'd suggest to close the issue here with a remark where to look instead.

So no one should be confused to accidentially write here instead of the generic issue...

Is this ok with you guys?

**Comment by malcolmh** [comment]
OK with me. Shall I close it, or will you?

**Comment by ehrenfeu** [comment]
Hehe, I'm just closing it now, before we start discussing who should do it :wink: 

:bulb: For future reference, plese see these issues  :bulb:
* OpenSeaMap/general#10
* OpenSeaMap/chart-sheet-properties#5
